import { useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { Activity, ArrowUpRight, Check, ChevronRight, CircleAlert, FileText, Gauge, Globe2, ImagePlus, Link2, Menu, Network, Search, ShieldCheck, Sparkles, X } from "lucide-react";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const issues = [{ level: "High", title: "Canonical tag is missing on 3 pages", detail: "Search engines may choose the wrong page version.", action: "Open canonical guide" }, { level: "High", title: "Sitemap has not been checked", detail: "A sitemap helps crawlers find your important pages.", action: "Check sitemap" }, { level: "Medium", title: "12 internal links need review", detail: "Broken paths can waste crawl time and frustrate visitors.", action: "Review links" }];
const integrations = [{ name: "Cloudflare", state: "Not verified", note: "Connect a token to check DNS and cache rules.", icon: ShieldCheck }, { name: "Google Search Console", state: "Not verified", note: "Inspection API access is needed for live status.", icon: Search }, { name: "Bing Webmaster", state: "Not verified", note: "Add site and sitemap access to verify.", icon: Globe2 }, { name: "Google AdSense", state: "Not verified", note: "Publisher status is not available in this workspace.", icon: Activity }];

function Status({ children, tone = "neutral" }) { return <span data-testid={`status-${tone}`} className={`status status-${tone}`}>{tone === "success" ? <Check size={13} /> : <CircleAlert size={13} />}{children}</span>; }
function Metric({ label, value, note, tone = "ink" }) { return <div data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`} className="metric"><span className="eyebrow">{label}</span><strong className={`metric-${tone}`}>{value}</strong><small>{note}</small></div>; }

function App() {
  const [page, setPage] = useState("Audit"); const [mobileOpen, setMobileOpen] = useState(false); const [url, setUrl] = useState(""); const [checking, setChecking] = useState(false); const [result, setResult] = useState(null); const [fileInfo, setFileInfo] = useState(null); const [topic, setTopic] = useState("");
  const nav = [{ name: "Audit", icon: Gauge }, { name: "Indexing", icon: Search }, { name: "Tools", icon: ImagePlus }, { name: "AutoBlog", icon: FileText }];
  const runCheck = async (event) => { event.preventDefault(); setChecking(true); setResult(null); try { const response = await axios.post(`${API}/inspect-url`, { url }); setResult(response.data); } catch (error) { setResult({ error: error.response?.data?.detail || "We could not check this URL. Try again." }); } finally { setChecking(false); } };
  const chooseFile = (event) => { const file = event.target.files?.[0]; if (!file) return; const image = new Image(); image.onload = () => setFileInfo({ name: file.name, size: `${(file.size / 1024 / 1024).toFixed(2)} MB`, width: image.width, height: image.height, valid: file.size < 5 * 1024 * 1024 && image.width >= 800 }); image.src = URL.createObjectURL(file); };
  const preview = useMemo(() => topic ? `A simple guide to ${topic}. We explain what to look for, how to compare choices, and which option may fit different budgets.` : "Your simple-English article preview will appear here.", [topic]);
  return <div className="workspace"><header className="topbar"><button className="brand" onClick={() => setPage("Audit")} data-testid="brand-home"><span className="brand-mark"><Sparkles size={17} /></span><span>Searchlight<small>SEO workbench</small></span></button><nav className="desktop-nav">{nav.map(({ name, icon: Icon }) => <button key={name} onClick={() => setPage(name)} className={page === name ? "nav-active" : ""} data-testid={`nav-${name.toLowerCase()}`}><Icon size={16} />{name}</button>)}</nav><button className="run-button" onClick={() => setPage("Indexing")} data-testid="run-audit-button"><Activity size={16} />Run check</button><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)} data-testid="mobile-menu-button">{mobileOpen ? <X /> : <Menu />}</button></header>
    {mobileOpen && <div className="mobile-nav">{nav.map(({ name }) => <button key={name} onClick={() => { setPage(name); setMobileOpen(false); }} data-testid={`mobile-nav-${name.toLowerCase()}`}>{name}<ChevronRight size={16} /></button>)}</div>}
    <main className="content"><div className="page-heading"><div><span className="eyebrow">SEARCHLIGHT DESK / {page.toUpperCase()}</span><h1>{page === "Audit" ? "Make every page easier to find." : page === "Indexing" ? "Find out why a page is rejected." : page === "Tools" ? "Repair the content assets." : "Write useful posts, without repeats."}</h1><p>{page === "Audit" ? "One calm view of the problems that can block search traffic. Start with the highest-impact repair." : "Use evidence from your own URL before changing code or settings."}</p></div><div className="freshness"><span className="signal-dot" />Live workspace<strong data-testid="last-checked">Not checked yet</strong></div></div>
    {page === "Audit" && <><section className="hero-grid"><div className="priority-panel"><div className="panel-label"><span>Priority queue</span><Status tone="warning">3 actions needed</Status></div><h2>Your next best move</h2><p>Start with canonical tags and your sitemap. These are simple code fixes that help crawlers understand which pages matter.</p><div className="progress-line"><span style={{ width: "64%" }} /></div><div className="progress-meta"><span>Site health estimate</span><strong>64 / 100</strong></div><button className="primary-button" onClick={() => setPage("Indexing")} data-testid="priority-check-indexing">Check a page <ArrowUpRight size={16} /></button></div><aside className="integration-panel"><div className="panel-label"><span>Connection health</span><Link2 size={16} /></div><h3>Evidence first</h3><p className="muted">These providers are shown as <b>Not verified</b> until a real response confirms them.</p>{integrations.map(({ name, state, note, icon: Icon }) => <div className="integration-row" key={name} data-testid={`integration-${name.toLowerCase().replaceAll(" ", "-")}`}><Icon size={17} /><div><strong>{name}</strong><small>{note}</small></div><Status>{state}</Status></div>)}</aside></section><section className="metrics"><Metric label="Indexable pages" value="—" note="Run a URL check to measure" /><Metric label="Broken links" value="12" note="3 high priority" tone="warning" /><Metric label="GEO opportunities" value="8" note="Local intent clusters" tone="success" /><Metric label="Backlinks" value="—" note="Provider not verified" /></section><section className="issue-section"><div className="section-heading"><div><span className="eyebrow">REPAIR QUEUE</span><h2>Three things worth fixing</h2></div><button className="text-button" onClick={() => setPage("Indexing")} data-testid="view-all-issues">View index check <ChevronRight size={16} /></button></div><div className="issue-list">{issues.map((item, index) => <article className="issue-row" key={item.title} data-testid={`issue-row-${index + 1}`}><span className={`issue-number issue-${item.level.toLowerCase()}`}>0{index + 1}</span><div><div className="issue-meta"><Status tone={item.level === "High" ? "error" : "warning"}>{item.level} impact</Status><span className="mono">SEO-{index + 1}0{index + 4}</span></div><h3>{item.title}</h3><p>{item.detail}</p></div><button className="repair-button" data-testid={`repair-issue-${index + 1}`}>{item.action}<ArrowUpRight size={15} /></button></article>)}</div></section></>}
    {page === "Indexing" && <section className="indexing-layout"><div className="form-panel"><span className="eyebrow">LIVE URL INSPECTOR</span><h2>Check one page</h2><p>We will fetch the page and report its response code, canonical, robots tag, and sitemap status. No guesswork.</p><form onSubmit={runCheck}><label htmlFor="url-check">Page URL</label><div className="input-row"><input id="url-check" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com/page" data-testid="indexing-url-input" /><button className="primary-button" disabled={checking || !url} data-testid="indexing-submit-button">{checking ? "Checking…" : "Inspect URL"}</button></div></form><div className="explain"><strong>Canonical is not robots.txt</strong><span>Canonical tells search engines which version is preferred. Robots controls crawling. A noindex tag asks them not to show a page.</span></div></div><div className="result-panel"><div className="panel-label"><span>Inspection result</span><Status tone={result && !result.error ? "success" : "neutral"}>{result ? (result.error ? "Needs action" : "Checked now") : "Waiting"}</Status></div>{!result && <div className="empty-state"><Search size={28} /><strong>Enter a URL to begin</strong><span>Results will include the exact evidence found in the HTML.</span></div>}{result?.error && <div className="error-box" data-testid="indexing-error"><CircleAlert /><strong>{result.error}</strong><span>Check the URL spelling, then try again.</span></div>}{result && !result.error && <div className="check-results" data-testid="indexing-results"><div className="result-url"><span className="eyebrow">FINAL URL</span><code>{result.url}</code><Status tone={result.status_code < 400 ? "success" : "error"}>{result.status_code}</Status></div>{[["Canonical", result.canonical, result.canonical_ok], ["Robots", result.robots, !result.noindex], ["Sitemap", `${result.sitemap_url} (${result.sitemap_status || "not found"})`, result.sitemap_status === 200], ["Page content", `${result.word_count} words · ${result.links} links`, result.word_count > 80]].map(([label, value, ok]) => <div className="check-row" key={label}><span>{ok ? <Check size={16} /> : <CircleAlert size={16} />}{label}</span><code>{value}</code><b>{ok ? "Looks good" : "Review"}</b></div>)}</div>}</div></section>}
    {page === "Tools" && <section className="tools-layout"><div className="tool-panel dominant"><div className="panel-label"><span>BACKGROUND REMOVER</span><Status>Provider not verified</Status></div><h2>Prepare a clean product image</h2><p>Upload an image to validate its dimensions and file weight. AI removal needs a connected provider before it can run.</p><label className="upload-box"><ImagePlus size={27} /><strong>{fileInfo ? fileInfo.name : "Drop JPG, PNG, or WebP here"}</strong><span>Maximum 5 MB · recommended minimum 800 × 800 px</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseFile} data-testid="background-image-input" /></label>{fileInfo && <div className="file-result" data-testid="image-quality-result"><div><span className="eyebrow">IMAGE CHECK</span><strong>{fileInfo.width} × {fileInfo.height} px · {fileInfo.size}</strong></div><Status tone={fileInfo.valid ? "success" : "warning"}>{fileInfo.valid ? "Ready to optimize" : "Needs a larger or smaller file"}</Status></div>}<div className="provider-note"><CircleAlert size={17} /><span><b>Not verified:</b> Background removal is not claiming success without an AI provider response.</span></div></div><aside className="tool-panel"><span className="eyebrow">UTILITY CHECKS</span><h3>Before you publish</h3>{["Keep the main product centered", "Use WebP when your CMS supports it", "Write alt text that describes the product"].map((text, i) => <div className="tip-row" key={text}><span>0{i + 1}</span>{text}</div>)}</aside></section>}
    {page === "AutoBlog" && <section className="autoblog-layout"><div className="form-panel"><span className="eyebrow">AUTOBLOG / STEP 01</span><h2>Build a useful draft</h2><p>Simple English, one clear topic, and a transparent affiliate note. Nothing publishes automatically.</p><label htmlFor="topic">Article topic</label><input id="topic" value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="Best budget headphones for remote work" data-testid="autoblog-topic-input" /><label htmlFor="affiliate">Affiliate product URL</label><input id="affiliate" placeholder="https://partner.example/product" data-testid="autoblog-affiliate-url-input" /><label htmlFor="disclosure">Affiliate disclosure</label><textarea id="disclosure" defaultValue="This article may contain affiliate links. We may earn a small commission at no extra cost to you." data-testid="autoblog-disclosure-input" /><button className="primary-button full" onClick={() => setTopic(topic || "your next product comparison")} data-testid="autoblog-preview-button">Create preview <Sparkles size={16} /></button></div><div className="preview-panel"><div className="panel-label"><span>DRAFT PREVIEW</span><Status tone="warning">Needs review</Status></div><h2>{topic || "Your article headline"}</h2><div className="preview-rule" /><p data-testid="autoblog-preview-text">{preview}</p><div className="preview-callout"><span className="eyebrow">PUBLISH CHECKLIST</span><span><Check size={14} /> Duplicate scan required</span><span><Check size={14} /> Affiliate disclosure required</span><span><Check size={14} /> Human review before publish</span></div></div></section>}
    </main><footer><span>Searchlight keeps provider claims honest.</span><span className="mono">v0.1 / evidence-led</span></footer></div>;
}

export default App;
